import numpy as np

##################################################
# Peak detection functions
##################################################

# returns a list with all times and values for detected peaks
def peakFind(time, s, fs):
    peakDeltaMin = 0.0005 # amplitude threshold
    minDistance = int(0.02 * fs) # minimum distance between peaks in samples

    peakValues = []
    peakTimes = []
    lastPeakIndex = -minDistance

    for i in range(1, len(s) - 1):

        # local max or min
        if ((s[i - 1] < s[i] and s[i + 1] < s[i]) or
            (s[i - 1] > s[i] and s[i + 1] > s[i])):

            # ignore small peaks
            if abs(s[i]) < peakDeltaMin:
                continue

            # enforce minimum spacing
            if i - lastPeakIndex < minDistance:
                continue

            peakValues.append(s[i])
            peakTimes.append(time[i])
            lastPeakIndex = i

    return np.array(peakValues), np.array(peakTimes)


# returns the threshold based on the detected peaks
def thresholdValue(peakValues):
    threshold = (np.max(peakValues) + np.min(peakValues)) * 0.4
    return threshold


# returns the first and last peak generated by a wheel
def firstLastWheelPeak(peakValues, peakTimes):
    threshold = thresholdValue(peakValues)

    wheelValues = []
    wheelTimes = []

    for i in range(len(peakValues)):
        if ((i == 0 or peakValues[i] < peakValues[i - 1]) and
            (i == len(peakValues) - 1 or peakValues[i] < peakValues[i + 1]) and
            (peakValues[i] < threshold)): # values have to be below the threshold to be peaks generated through train wheels

            wheelValues.append(peakValues[i])
            wheelTimes.append(peakTimes[i])

    if len(wheelValues) == 0:
        return None, None, None, None

    return (
        wheelValues[0], wheelTimes[0],      # first wheel
        wheelValues[-1], wheelTimes[-1]     # last wheel
    )


# returns the peak before the first wheel and after the last one
def firstLastPeak(peakValues, peakTimes):
    threshold = thresholdValue(peakValues)

    wheelIndices = []

    for i in range(len(peakValues)):
        if ((i == 0 or peakValues[i] < peakValues[i-1]) and
            (i == len(peakValues) - 1 or peakValues[i] < peakValues[i+1]) and 
            (peakValues[i] < threshold)):

            wheelIndices.append(i)
    
    if len(wheelIndices) == 0:
        return None, None, None, None
    
    first_idx = wheelIndices[0]
    last_idx = wheelIndices[-1]

    before_idx = first_idx - 1 if first_idx > 0 else None
    after_idx = last_idx + 1 if last_idx < len(peakValues) - 1 else None

    return(
        peakValues[before_idx] if before_idx is not None else peakValues[first_idx],
        peakTimes[before_idx] if before_idx is not None else peakTimes[first_idx],
        peakValues[after_idx] if after_idx is not None else peakValues[last_idx],
        peakTimes[after_idx] if after_idx is not None else peakTimes[last_idx]
    )


# returns a list of all times a wheel pass on the sensor and its value
def downPeak(peakValues, peakTimes):
    threshold = thresholdValue(peakValues)
    firstValue, firstTime, lastValue, lastTime = firstLastPeak(peakValues, peakTimes)

    downValues = []
    downTimes = []

    for i in range(1, len(peakValues)):

        if peakTimes[i] < firstTime or peakTimes[i] > lastTime:
            continue

        if peakValues[i] >= threshold:
            continue

        if peakValues[i-1] > peakValues[i]:
            downValues.append(peakValues[i])
            downTimes.append(peakTimes[i])

    return np.array(downValues), np.array(downTimes)